services:
  gunthy:
    build: .
    container_name: gunthy-gui
    ports:
      - "5002:5002"
    volumes:
      - gunthy-data:/home/gunthy
    environment:
      # Styr API-URL och port för config.json
      #CONFIG_API_URL: http://iptogb:port
      #CONFIG_PORT: 5002
    restart: unless-stopped

volumes:
  gunthy-data:
